mermaid.initialize({
  startOnLoad: true,
  theme: 'base',
  themeVariables: {
    darkMode: true,
    primaryColor: '#1e1e2e',
    primaryTextColor: '#cdd6f4',
    primaryBorderColor: '#585b70',
    lineColor: '#a6adc8',
    secondaryColor: '#181825',
    secondaryTextColor: '#cdd6f4',
    secondaryBorderColor: '#45475a',
    tertiaryColor: '#11111b',
    tertiaryTextColor: '#bac2de',
    tertiaryBorderColor: '#45475a',
    background: '#0b0b14',
    mainBkg: '#1e1e2e',
    nodeBorder: '#585b70',
    nodeTextColor: '#cdd6f4',
    clusterBkg: '#11111b',
    clusterBorder: '#45475a',
    defaultLinkColor: '#a6adc8',
    titleColor: '#cdd6f4',
    edgeLabelBackground: '#11111b',
    textColor: '#cdd6f4',
    actorTextColor: '#cdd6f4',
    actorBkg: '#1e1e2e',
    actorBorder: '#585b70',
    actorLineColor: '#a6adc8',
    signalColor: '#a6adc8',
    signalTextColor: '#cdd6f4',
    labelBoxBkgColor: '#181825',
    labelBoxBorderColor: '#45475a',
    labelTextColor: '#cdd6f4',
    loopTextColor: '#a6adc8',
    noteBkgColor: '#181825',
    noteTextColor: '#bac2de',
    noteBorderColor: '#45475a',
    activationBkgColor: '#1e1e2e',
    activationBorderColor: '#585b70',
    sequenceNumberColor: '#cdd6f4',
    sectionBkgColor: '#181825',
    altSectionBkgColor: '#11111b',
    taskBkgColor: '#1e1e2e',
    taskTextColor: '#cdd6f4',
    stateBkg: '#1e1e2e',
    stateTextColor: '#cdd6f4',
    stateLabelColor: '#cdd6f4',
    transitionColor: '#a6adc8',
    fontFamily: '"Inter", "Segoe UI", system-ui, sans-serif'
  },
  flowchart: { curve: 'basis', padding: 20 },
  sequence: { mirrorActors: false, messageMargin: 40, boxMargin: 8, noteMargin: 8, actorMargin: 60, width: 180 }
});
